# Generated by Django 5.0 on 2023-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=3)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
